name: CI

on: 
  push:
    branches:    
      - develop 

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: test/install
      run: |
        npm install
      
    - name: test/build
      run: |
        npm run build

    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        command_timeout: 20m
        script: |
          node -v
          npm -v
          cd ${{ secrets.SERVER_PATH }}
          git checkout develop
          git pull --rebase origin
          npm install
          npm run build
